Added closeOnScroll parameter to controll scroll listener
selecthub/v-img pull request #1
Opened 2018-09-21 10:32 UTC by BartoszJurkiewicz

2018-09-21 11:09 UTC, pjar commented on lib/ImgScreen.vue
> +      closeOnScroll: false
Since previously this was the default behaviour, I would intially expect this to be set to true.

2018-09-21 11:16 UTC, pjar commented on lib/ImgScreen.vue
> +    }
Why this way vs. solving this conditional in `created()`?

2018-09-21 11:17 UTC, pjar commented on lib/ImgScreen.vue
> +  }
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

2018-09-21 11:19 UTC, pjar commented on lib/index.js
> +    closeOnScroll: false,
Same as https://github.com/selecthub/v-img/pull/1/files#r219461752

2018-09-21 11:20 UTC, pjar requested changes
@BartoszJurkiewicz Please check comments

2018-09-21 12:26 UTC, BartoszJurkiewicz commented on lib/ImgScreen.vue
> +    }
Because closeOnScroll has initial value set to true (previously false) and is updated from elements dataset when gallery is opened

2018-10-09 19:45 UTC, pjar approved these changes

2018-10-09 19:46 UTC, merged